export const AUTH_CONSTANTS = Object.freeze({
  ACCESS_TOKEN_EXPIRES_IN: "15m",
  REFRESH_TOKEN_EXPIRES_IN: "30d",

  PASSWORD_MIN_LENGTH: 8,
  PASSWORD_MAX_LENGTH: 128,

  NAME_MIN_LENGTH: 2,
  NAME_MAX_LENGTH: 100,

  EMAIL_MAX_LENGTH: 254,

  REFRESH_TOKEN_BYTES: 32,

  ERROR_CODES: Object.freeze({
    INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
    EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
    ACCOUNT_SUSPENDED: "ACCOUNT_SUSPENDED",
    ACCOUNT_DEACTIVATED: "ACCOUNT_DEACTIVATED",
    INVALID_REFRESH_TOKEN: "INVALID_REFRESH_TOKEN",
    SESSION_REVOKED: "SESSION_REVOKED",
    SESSION_EXPIRED: "SESSION_EXPIRED",
    AUTHENTICATION_REQUIRED: "AUTHENTICATION_REQUIRED",
    EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",
  }),
});
